### ISSUE TITLE
icarus theme duplicates image caption

### ISSUE THREAD

**Issue by matthiasbeyer** [liwenyip/hugo-easy-gallery#23]
Hi,

the icarus theme (at least the version I use, which is 8d7dd851703fcddf0c89f774265caf24cdfeade3 from the hugo-icarus-theme) puts a caption right _over_ the images in a gallery.

I did this ugly hack which fixes the issue for me.

```css
/* Hack
 *
 * This is a hack:
 *
 * hugo-easy-gallery puts a "caption" into the image.
 * my hugo theme (icarus) formats a "class = 'caption'" for images.
 * But as the hugo easy gallery plugin renders its own caption with the
 * <figcaption> tag, we don't need to see that hugo caption.
 *
 * So we hide it.
 */
.img .caption {
  display: none
}
```

And I included that css file in my site via

```
{{- if not ($.Page.Scratch.Get "figurecount") }}<link rel="stylesheet" href="/css/gallery-caption.css" />{{ end }}
```

in `/layouts/shortcodes/figure.html`.

Newer versions of the icarus theme might not have that issue.

---

Feel free to close this issue right away, I don't expect you to do anything but notice this. This issue was filed only as a documentation of the issue.
